import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AmplifyProvider from "@/components/auth/AmplifyProvider";
import { QueryProvider } from "../providers/QueryProvider";
import Header from "@/components/ui/Header";
import { ToastProvider } from "../components/ui/ToastProvider";
import { AuthProvider } from "../contexts/AuthContext";
import { ChatGenerationProvider } from "@/contexts/ChatGenerationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-hidden flex flex-col`}
      >
        <AmplifyProvider>
          <QueryProvider>
            <ToastProvider>
              <AuthProvider>
                <ChatGenerationProvider>
                  <Header />
                  <main className="flex-1 h-full overflow-hidden relative">
                    {children}
                  </main>
                </ChatGenerationProvider>
              </AuthProvider>
            </ToastProvider>
          </QueryProvider>
        </AmplifyProvider>
      </body>
    </html>
  );
}
