/**
 * APIエラーコード
 * フロントエンドで多言語対応するための識別子
 */
export enum ErrorCode {
  // --- 400 Bad Request: 入力不備系 ---
  VALIDATION_FAILED = "VALIDATION_FAILED", // DTOバリデーションエラーなど
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE", // 許可されていない拡張子
  INVALID_PARAMETER = "INVALID_PARAMETER", // パラメータが無効

  INVALID_INPUT = "INVALID_INPUT", // その他の入力不正
  MISSING_PARAMETER = "MISSING_PARAMETER", // パラメータが不足している

  // --- 401 Unauthorized / 403 Forbidden: 認証・権限系 ---
  // 基本的に401/403はステータスコードだけで十分だが、詳細な理由が必要な場合に利用
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  PERMISSION_DENIED = "PERMISSION_DENIED", // リソースへのアクセス権がない

  // --- 404 Not Found: リソース不在 ---
  // 基本的に404はステータスコードだけで十分
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // --- 409 Conflict: 競合 ---
  DOCUMENT_ALREADY_EXISTS = "DOCUMENT_ALREADY_EXISTS", // 同名の文書が存在
  STATE_CONFLICT = "STATE_CONFLICT", // 処理中のため操作できない

  // --- 500 Internal Server Error: サーバー内部エラー ---
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR", // 予期せぬエラー
  DB_OPERATION_FAILED = "DB_OPERATION_FAILED", // DynamoDB等の操作失敗
  BEDROCK_API_ERROR = "BEDROCK_API_ERROR", // AIサービスの呼び出し失敗
  S3_OPERATION_FAILED = "S3_OPERATION_FAILED", // ストレージ操作失敗

  DOCUMENTS_FILE_EMPTY = "DOCUMENTS_FILE_EMPTY", // ファイルが空
  DOCUMENTS_FILE_TOO_LARGE = "DOCUMENTS_FILE_TOO_LARGE", // ファイルサイズが大きすぎる
  DOCUMENTS_UNSUPPORTED_FILE_TYPE = "DOCUMENTS_UNSUPPORTED_FILE_TYPE", // サポートされていないファイルタイプ
  DOCUMENTS_INVALID_FILENAME = "DOCUMENTS_INVALID_FILENAME", // ファイル名が無効
  DOCUMENTS_INVALID_FILENAME_LENGTH_LIMIT = "DOCUMENTS_INVALID_FILENAME_LENGTH_LIMIT", // ファイル名の文字列制限
  DOCUMENTS_TAG_LENGTH_LIMIT = "DOCUMENTS_TAG_LENGTH_LIMIT", // タグの文字列制限
  DOCUMENTS_TAG_INVALID = "DOCUMENTS_TAG_INVALID", // タグが無効
  DOCUMENTS_TAGS_TOO_MANY = "DOCUMENTS_TAGS_TOO_MANY", // タグが多すぎる
  DOCUMENTS_NOT_FOUND = "DOCUMENTS_NOT_FOUND", // ドキュメントが見つからない
  DOCUMENTS_UPLOAD_FAILED = "DOCUMENTS_UPLOAD_FAILED", // アップロードに失敗した
  DOCUMENTS_PROCESSING_FAILED = "DOCUMENTS_PROCESSING_FAILED", // 処理に失敗した
  DOCUMENTS_DELETE_FAILED = "DOCUMENTS_DELETE_FAILED", // 削除に失敗した
  DOCUMENTS_EXTRACTED_TEXT_EMPTY = "DOCUMENTS_EXTRACTED_TEXT_EMPTY", // 抽出されたテ
  // キストが空
  DOCUMENTS_NOT_READY_FOR_DOWNLOAD = "DOCUMENTS_NOT_READY_FOR_DOWNLOAD", // ダウンロード準備ができていない

  // Chat API エラー
  CHAT_SESSION_NAME_TOO_LONG = "CHAT_SESSION_NAME_TOO_LONG", // セッション名が長すぎ
  CHAT_SESSION_NAME_EMPTY = "CHAT_SESSION_NAME_EMPTY", // セッション名が空
  CHAT_QUERY_EMPTY = "CHAT_QUERY_EMPTY",
  CHAT_QUERY_TOO_LONG = "CHAT_QUERY_TOO_LONG",
  CHAT_SESSION_NOT_FOUND = "CHAT_SESSION_NOT_FOUND",
  CHAT_HISTORY_NOT_FOUND = "CHAT_HISTORY_NOT_FOUND",
  CHAT_BEDROCK_ERROR = "CHAT_BEDROCK_ERROR",
  CHAT_NO_DOCUMENTS = "CHAT_NO_DOCUMENTS",
  CHAT_TOO_MANY_MESSAGES = "CHAT_TOO_MANY_MESSAGES",
  CHAT_COMMENT_TOO_LONG = "CHAT_COMMENT_TOO_LONG",
  CHAT_FEEDBACK_REASONS_INVALID = "CHAT_FEEDBACK_REASONS_INVALID",
  CHAT_FEEDBACK_REASONS_EMPTY = "CHAT_FEEDBACK_REASONS_EMPTY",
}
